# Default values for dash.

replicaCount: 1

image:
  repository: arrajput/dash
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
ingress:
  enabled: true
  
  host: "fullnode.dash"
  paths: 
    - "/"
  tls: []

resources: {}
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 900m
      memory: 1000Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
