apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dgb-volume-claim-{{ .Release.Name }}
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
