apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: digibyte-node-ingress-web
  labels:
    {{- include "digibyte.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.ingress.certresolver }}
    traefik.ingress.kubernetes.io/router.tls.certresolver: {{ .Values.ingress.certresolver }}
  {{- end }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        - path: /
          backend:
            serviceName: web-digibyte-node
            servicePort: 80
