{{- if .Values.ingress.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: node-ingress-rpc
spec:
  entryPoints:
    - rpc
  routes:
    - match: HostSNI(`*`)
      services:
        - name: rpc-digibyte-node
          port: 14022
{{- end }}
