apiVersion: v1
kind: Service
metadata:
  name: ssh-digibyte-node
  labels:
    {{- include "digibyte.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 2020
      targetPort: 22
  selector:
    {{- include "digibyte.selectorLabels" . | nindent 4 }}
