apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: crypto-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: test80.tfgw-testnet-01.gateway.tf
      http:
        paths:
        - path: /
          backend:
            serviceName: cryptpad-service
            servicePort: 8080
