apiVersion: v1
kind: Service
metadata:
  name: cryptpad-service
  labels:
    {{- include "cryptpad-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "cryptpad-test.selectorLabels" . | nindent 4 }}