apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: taiga-ingress
spec:
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
        - path: /
          backend:
            serviceName: taiga-service
            servicePort: 80
