# Default values for digibyte.
replicaCount: 1

image:
  repository: arrajput/digibyte
  pullPolicy: Always
  tag: "2.5"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

ingress:
  enabled: true
  
  host: "fullnode.digibyte"
  paths: 
    - "/"
  tls: []
 
# These values should be overrided from the chatflow (rpcuser & rpcuser)
env:          
  "rpcuser": "tfnow" 
  "rpcpasswd": "tfdgb2020"

resources: 
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 900m
      memory: 1000Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
