# Default values for digibyte.
replicaCount: 1

image:
  repository: arrajput/digibyte
  pullPolicy: Always
  tag: "2.5"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

ingress:
  enabled: true
  
  host: "fullnode.digibyte"
  paths: 
    - "/"
  tls: []

resources: 
    limits:
      cpu: 2000m
      memory: 4096Mi
    requests:
      cpu: 1800m
      memory: 4000Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
