{{- $svcName := printf "%s-%s" .Values.servicecryptpad.name .Release.Name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $svcName }}
  labels:
    {{- include "cryptpad.labels" . | nindent 4 }}
spec:
  type: {{ .Values.servicecryptpad.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.servicecryptpad.port }}
      targetPort: {{ .Values.servicecryptpad.targetPort }}
  selector:
    {{- include "cryptpad.selectorLabels" . | nindent 4 }}