apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
spec:
  capacity:
    storage: {{ .Values.volume.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""
  hostPath:
    path: {{ .Values.volume.hostPath }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.volume.size }}
  storageClassName: ""
  volumeName: data
