apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ include "cryptpad.fullname" . }}-data"
  labels:
    backupType: {{ .Values.threefoldVdc.backup }}
    {{- include "cryptpad.labels" . | nindent 4 }}
spec:
  capacity:
    storage: "{{ .Values.volume.size }}Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: "local-storage"
  local:
    path: {{ .Values.volume.hostPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - example-node

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "cryptpad.fullname" . }}-data-claim"
  labels:
    backupType: {{ .Values.threefoldVdc.backup }}
    {{- include "cryptpad.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: "{{ .Values.volume.size }}Gi"
  storageClassName: ""
  volumeName: "{{ include "cryptpad.fullname" . }}-data"
