{{- if .Values.ingress.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: node-ingress
spec:
  entryPoints:
    - p2p
  routes:
    - match: HostSNI(`*`)
      services:
        - name: p2p-dash-node
          port: 9999
{{- end }}
